baseURL = "https://ethanvu.github.io/"
languageCode = "en-us"
title = "Ethan Vu"
theme = "newsroom"
author = "ethanvu"
copyright = "Copyright © 2020, ethavu, Weru, and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 10
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"
